---
- name: (install) install deb packages
  ansible.builtin.apt:
    name: "{{ takel_hg_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) install pip packages
  ansible.builtin.include_role:
    name: takel_pip
  vars:
    takel_pip_packages: "{{ takel_hg_pip_packages }}"

- name: (configure) configure root user
  ansible.builtin.include_role:
    name: takel_user
  vars:
    takel_user_name: root
    takel_user_group: root
    takel_user_home: /root
    takel_user_create: false
