---
- name: (install) install deb packages
  apt:
    name: "{{ takel_hg_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) install dulwich pip package
  pip:
    name: dulwich
    state: present

- name: (install) create hg extension dir
  file:
    path: "{{ takel_hg_extension_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: (install) clone hg-git extension
  hg:
    repo: "{{ takel_hg_extension_repo_hggit }}"
    dest: "{{ takel_hg_extension_dir }}/hg-git"
