---
- name: default
  hosts: all
  pre_tasks:
    - name: (converge) install prerequisites
      package:
        name: "{{ item }}"
      loop:
        - ca-certificates
        - curl
        - gnupg
        - procps
        - python3-yaml
        - sudo
  roles:
    - takel-rvm
    - takel-gem
    - takel-takelage
