---
takel_base_deb_install_packages:
  - apt-transport-https
  - aptitude
  - bat
  - ca-certificates
  - curl
  - gnupg
  - git
  - iproute2
  - iputils-ping
  - jq
  - locales
  - parallel
  - procps
  - python3-jmespath
  - rsync
  - rsyslog
  - tmux
  - tree
  - vim
  - wget
  - make
