# frozen_string_literal: true

require 'rake'

namespace :project do
  desc 'Create and deploy prod image to dockerhub'
  task prod: %w[git:warn
                dockerhub:login
                rubylint
                rake ansible:prod:molecule:lint
                takelscripts
                images:update
                images:takelage:prod:build
                images:takelage:prod:molecule:test
                git:tag
                dockerhub:tag
                dockerhub:push]
end
