default:
  image:
    name: takelwerk/takelbuild:latest-arm64
    entrypoint: ["/usr/bin/tail -f /dev/null"]
  services:
    - name: docker:dind
      command: [ "dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false" ]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''  # unset means: "unencrypted"

stages:
  - build

build-takelbeta:
  stage: build
  script:
    # Lint ruby
    - rake rubylint

    # Lint takelbeta
    - rake images:takelbeta:molecule:lint

    # Test takelscripts
    - rake takelscripts

    # Update debian base image
    - rake images:project:update

    # Build image with packer
    - rake images:takelbeta:build

    # Test takelage takelbeta image
    - rake images:takelbeta:molecule:test

    # Login to dockerhub
    - docker login --username takelwerk --password $DOCKERHUB_TOKEN

    # Tag and push image
    - rake dockerhub:takelbeta:tag:latest:arm64
    - rake dockerhub:takelbeta:push:latest:arm64
    - rake dockerhub:takelbeta:tag:version:arm64
    - rake dockerhub:takelbeta:push:version:arm64

    # Pull amd64 images
    - rake dockerhub:takelbeta:pull:latest:amd64
    - rake dockerhub:takelbeta:pull:version:amd64

    # Create and push docker manifests
    - rake dockerhub:takelbeta:manifest:create:latest
    - rake dockerhub:takelbeta:manifest:push:latest
    - rake dockerhub:takelbeta:manifest:create:version
    - rake dockerhub:takelbeta:manifest:push:version

build-takelage:
  stage: build
  script:
    # Lint ruby
    - rake rubylint

    # Lint takelage
    - rake images:project:molecule:lint

    # Test takelscripts
    - rake takelscripts

    # Update debian base image
    - rake images:project:update

    # Build image with packer
    - rake images:project:build

    # Test takelage takelage image
    - rake images:project:molecule:test

    # Login to dockerhub
    - docker login --username takelwerk --password $DOCKERHUB_TOKEN

    # Tag and push image
    - rake dockerhub:project:tag:latest:arm64
    - rake dockerhub:project:push:latest:arm64
    - rake dockerhub:project:tag:version:arm64
    - rake dockerhub:project:push:version:arm64

    # Pull amd64 images
    - rake dockerhub:project:pull:latest:amd64
    - rake dockerhub:project:pull:version:amd64

    # Create and push docker manifests
    - rake dockerhub:project:manifest:create:latest
    - rake dockerhub:project:manifest:push:latest
    - rake dockerhub:project:manifest:create:version
    - rake dockerhub:project:manifest:push:version

build-takelbuild:
  stage: build
  script:
    # Lint ruby
    - rake rubylint

    # Lint takelbuild
    - rake images:takelbuild:molecule:lint

    # Test takelscripts
    - rake takelscripts

    # Update debian base image
    - rake images:project:update

    # Build takelbuild intermediate image with packer
    - rake images:takelbuild:build:to:06-ruby

    # Build takelbuild image from intermediate image with packer
    - rake images:takelbuild:build:from:06-ruby

    # Test takelbuild takelbuild image
    - rake images:takelbuild:molecule:test

    # Login to dockerhub
    - docker login --username takelwerk --password $DOCKERHUB_TOKEN

    # Tag and push image
    - rake dockerhub:takelbuild:tag:latest:arm64
    - rake dockerhub:takelbuild:push:latest:arm64
    - rake dockerhub:takelbuild:tag:version:arm64
    - rake dockerhub:takelbuild:push:version:arm64

    # Pull amd64 images
    - rake dockerhub:takelbuild:pull:latest:amd64
    - rake dockerhub:takelbuild:pull:version:amd64

    # Create and push docker manifests
    - rake dockerhub:takelbuild:manifest:create:latest
    - rake dockerhub:takelbuild:manifest:push:latest
    - rake dockerhub:takelbuild:manifest:create:version
    - rake dockerhub:takelbuild:manifest:push:version
