---
# project settings
name: takelage-dev
version: 0.43.2

pipelines:
  - prod

local_user: packer_local

images:
  project:
    base_user: takelwerk
    base_repo: takelruby
    base_tag: latest
    target_user: takelwerk
    target_repo: takelage
    omit_pipeline_name: prod
    layers:
      - site
  takelbeta:
    base_user: takelwerk
    base_repo: takelruby
    base_tag: latest
    target_user: takelwerk
    target_repo: takelbeta
    omit_pipeline_name: prod
    layers:
      - site
  takelbuild:
    base_user: takelwerk
    base_repo: takelruby
    base_tag: latest
    target_user: takelwerk
    target_repo: takelbuild
    omit_pipeline_name: prod
    keep_interim_images: false
    layers:
      - system
      - python
      - docker
      - packer
      - ruby
      - takelage
