---
name: takelage-dev
version: 0.36.14
local_user: packer_local
dockerhub_base_user: takelage
dockerhub_base_repo: takelslim
dockerhub_user: takelage
dockerhub_repo: takelage
dockerhub_tag: prod
pipelines:
  - prod
  - stage
  - dev
images:
  takelage:
    layers:
      - site
  takeldev:
    layers:
      - system
      - python
      - docker
      - packer
      - gopass
      - bit
      - gcloud
      - hugo
      - terra
      - ruby
      - takelage
  takelweb:
    layers:
      - system
      - python
      - docker
      - packer
      - gopass
      - gcloud
      - ruby
      - takelage
