---
name: takelage-dev
version: 0.37.9

# results in packer_local/myproject-mypipeline:latest
local_user: packer_local

# pull
dockerhub_base_user: takelage
dockerhub_base_repo: takelslim

# push
dockerhub_user: takelage
dockerhub_repo: takelage
dockerhub_tag: prod

pipelines:
  - prod

images:
  takelage:
    layers:
      - site
  takeldev:
    layers:
      - system
      - python
      - docker
      - packer
      - gopass
      - bit
      - gcloud
      - hugo
      - terra
      - ruby
      - takelage
