---
name: takelage-dev
version: 0.54.6

local_user: packer_local

images:
  project:
    base_user: takelwerk
    base_repo: takelruby
    base_tag: latest
    target_user: takelwerk
    target_repo: takelage
    layers:
      - site
  takelbeta:
    base_user: takelwerk
    base_repo: takelruby
    base_tag: latest
    target_user: takelwerk
    target_repo: takelbeta
    layers:
      - site
  takelbuild:
    base_user: takelwerk
    base_repo: takelruby
    base_tag: latest
    target_user: takelwerk
    target_repo: takelbuild
    keep_interim_images: false
    layers:
      - system
      - mercurial
      - python
      - docker
      - packer
      - ruby
      - takelage
