---
# project settings
name: takelage-dev
version: 0.38.8

pipelines:
  - prod

local_user: packer_local

images:
  project:
    base_user: takelage
    base_repo: takelslim
    base_tag: latest
    target_user: takelage
    target_repo: takelage
    omit_pipeline_name: prod
    layers:
      - site
  takeldev:
    base_user: takelage
    base_repo: takelslim
    base_tag: latest
    keep_interim_images: false
    layers:
      - system
      - python
      - docker
      - packer
      - ruby
      - takelage
