---
name: takelage-dev
version: 0.35.4
local_user: packer_local
dockerhub_base_user: takelage
dockerhub_base_repo: takelslim
dockerhub_user: takelage
dockerhub_repo: takelage
dockerhub_tag: prod
images:
  takelage:
    layer:
      - site.yml
  takeldev:
    layer:
      - system
      - python
      - docker
      - packer
      - gopass
      - bit
      - gcloud
      - hugo
      - terra
      - ruby
      - takelage
  takelweb:
    layer:
      - system
      - python
      - docker
      - packer
      - gopass
      - gcloud
      - ruby
      - takelage
