---
- name: (main) include version
  ansible.builtin.import_tasks: version.yml
  tags:
    - takel
    - takel_kubernetes
    - takel_kubernetes_version

- name: (main) include repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - takel
    - takel_kubernetes
    - takel_kubernetes_repository
  when: takel_kubernetes_google_cloud_repository_install

- name: (main) include install
  ansible.builtin.import_tasks: install.yml
  tags:
    - takel
    - takel_kubernetes
    - takel_kubernetes_install

- name: (main) include completion
  ansible.builtin.import_tasks: completion.yml
  tags:
    - takel
    - takel_kubernetes
    - takel_kubernetes_completion

- name: (main) include cleanup
  ansible.builtin.import_tasks: cleanup.yml
  tags:
    - takel
    - takel_kubernetes
    - takel_kubernetes_cleanup
