---
- name: (repository) add google cloud key
  ansible.builtin.get_url:
    url: "{{ takel_kubernetes_google_cloud_repository_key }}"
    dest: "{{ takel_kubernetes_google_cloud_repository_keyfile }}"
    owner: root
    group: root
    mode: 0644
  when: takel_kubernetes_google_cloud_repository_install

- name: (repository) add google kubernetes repo
  ansible.builtin.apt_repository:
    repo: "{{ takel_kubernetes_google_cloud_repository }}"
    filename: "{{ takel_kubernetes_google_cloud_repository_filename }}"
  when: takel_kubernetes_google_cloud_repository_install
