---
- name: (version) get k3d version
  ansible.builtin.shell:
    cmd: curl -s https://github.com/k3d-io/k3d/releases | grep '/k3d-io/k3d/releases/tag/' | head -1 | sed -E 's#.*">v(.*)</a>.*#\1#'  # yamllint disable-line rule:line-length
  register: takel_kubernetes_k3d_latest_version
  delegate_to: localhost

- name: (version) set k3d version
  ansible.builtin.set_fact:
    takel_kubernetes_k3d_version: >-
      {{ takel_kubernetes_k3d_latest_version.stdout }}

- name: (version) get helm version
  ansible.builtin.shell:
    cmd: curl -s https://github.com/k3d-io/k3d/releases | grep '/k3d-io/k3d/releases/tag/' | head -1 | sed -E 's#.*">v(.*)</a>.*#\1#'  # yamllint disable-line rule:line-length
  register: takel_kubernetes_k3d_latest_version
  delegate_to: localhost

- name: (version) set helm version
  ansible.builtin.set_fact:
    takel_kubernetes_k3d_version: >-
      {{ takel_kubernetes_k3d_latest_version.stdout }}

- name: (version) install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true

- name: (version) install github3.py
  ansible.builtin.pip:
    name: github3.py
    extra_args: --break-system-packages

- name: (version) get latest release of k3d
  community.general.github_release:
    user: k3d-io
    repo: k3d
    action: latest_release
  register: takel_kubernetes_k3d_latest_version
  when:
    - takel_kubernetes_k3d_install
    - takel_kubernetes_k3d_version == 'latest'

- name: (version) extract k3d version
  ansible.builtin.set_fact:
    takel_kubernetes_k3d_version: >-
      {{ takel_kubernetes_k3d_latest_version.tag | split('v') | last }}
  when:
    - takel_kubernetes_k3d_install
    - takel_kubernetes_k3d_version == 'latest'

- name: (version) get latest release of helm
  community.general.github_release:
    user: helm
    repo: helm
    action: latest_release
  register: takel_kubernetes_helm_latest_version
  when:
    - takel_kubernetes_helm_install
    - takel_kubernetes_helm_version == 'latest'

- name: (version) extract helm version
  ansible.builtin.set_fact:
    takel_kubernetes_helm_version: >-
      {{ takel_kubernetes_helm_latest_version.tag | split('v') | last }}
  when:
    - takel_kubernetes_helm_install
    - takel_kubernetes_helm_version == 'latest'
