---
- name: (version) get k3d version
  ansible.builtin.shell:
    cmd: "{{ takel_kubernetes_k3d_version_cmd }}"
  register: takel_kubernetes_k3d_latest_version
  delegate_to: localhost
  changed_when: false

- name: (version) set k3d version
  ansible.builtin.set_fact:
    takel_kubernetes_k3d_version: >-
      {{ takel_kubernetes_k3d_latest_version.stdout }}

- name: (version) get helm version
  ansible.builtin.shell:
    cmd: "{{ takel_kubernetes_helm_version_cmd }}"
  register: takel_kubernetes_helm_latest_version
  delegate_to: localhost
  changed_when: false

- name: (version) set helm version
  ansible.builtin.set_fact:
    takel_kubernetes_helm_version: >-
      {{ takel_kubernetes_helm_latest_version.stdout }}

- name: (version) install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
