# frozen_string_literal: true

require 'rake'

namespace :dockerhub do
  namespace :multipostgres do
    desc 'Create and deploy multipostgres image to dockerhub'
    task '11': %w[dockerhub:multipostgres:11:registry:login
                  rubylint
                  image:docker:multipostgres:11
                  dockerhub:multipostgres:11:registry:tag
                  dockerhub:multipostgres:11:registry:push]
  end
end
