---
- name: (install) install deb packages
  package:
    name: "{{ takel_gcloud_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) copy installation script
  copy:
    src: install_google_cloud_sdk.bash
    dest: /tmp
    mode: 0755
  register: gcloud_script_copied
  changed_when: false

- name: (install) detect installation
  stat:
    path: /opt/google-cloud-sdk
  register: google_cloud_sdk

# noqa 503 == acknowledge to ansible-lint that we should use a handler
- name: (install) run installation script
  command: >-
    /tmp/install_google_cloud_sdk.bash
    --disable-prompts
    --install-dir={{ takel_gcloud_installation_root }}
  when: not google_cloud_sdk.stat.exists

- name: (install) remove installation script
  file:
    path: /tmp/install_google_cloud_sdk.bash
    state: absent
  changed_when: false

- name: (install) install gcloud components
  command: >-
    {{ takel_gcloud_installation_root}}/google-cloud-sdk/bin/gcloud
    --quiet components install alpha beta
  changed_when: false
