---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_gcloud
    - takel_gcloud_install

- name: (main) include completion
  import_tasks: completion.yml
  tags:
    - takel
    - takel_gcloud
    - takel_gcloud_completion
