---
- name: (install) install deb packages
  apt:
    name: "{{ takel_gopass_deb_install_packages }}"
    state: present
    update_cache: true


- name: (install) copy pass template
  template:
    src: pass.j2
    dest: /usr/local/bin/pass
    owner: root
    group: root
    mode: 0755
