# frozen_string_literal: true

require 'rake'

namespace :dockerhub do
  desc 'Create and deploy base image to dockerhub'
  task base: %w[dockerhub:base:registry:login
                rubylint
                image:base:debian_10_systemd
                dockerhub:base:registry:tag
                dockerhub:base:registry:push]
end
