---
- name: (install) install gems
  community.general.gem:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default('') }}"
    user_install: false
    norc: true
  loop: "{{ takel_gem_gems }}"
