---
- name: (install) install packages
  ansible.builtin.apt:
    name: "{{ takel_gem_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) install gems
  community.general.gem:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default('') }}"
    user_install: false
    norc: true
  loop: "{{ takel_gem_gems }}"
