---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_gem
    - takel_gem_install

- name: (main) include profile
  import_tasks: profile.yml
  tags:
    - takel
    - takel_gem
    - takel_gem_profile
