---
- name: (completion) create completion dir
  ansible.builtin.file:
    path: "{{ takel_mutagen_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: (completion) create completion file
  ansible.builtin.command: >-
    mutagen generate
    --bash-completion-script
    {{ takel_mutagen_bash_completion }}
  args:
    creates: "{{ takel_mutagen_bash_completion }}"
