# frozen_string_literal: true

require 'rake'

namespace :local do
  namespace :debug do
    namespace :prod do |env|
      @cmd_local_list.except(:features, :verify).each do |task, command|
        desc "#{task} #{env.scope.head} image locally"
        task task do
          @commands << format(
            command,
            project_environment: env.scope.head,
            molecule_command: task
          )
        end
      end
    end
  end
end
