---
- name: (configure) create completion dir
  file:
    path: "{{ takel_mutagen_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: (configure) create completion file
  command: >-
    mutagen generate
    --bash-completion-script
    {{ takel_mutagen_bash_completion }}
  args:
    creates: "{{ takel_mutagen_bash_completion }}"
