# frozen_string_literal: true

require 'rake'

cmd_dockerhub_registry_login = 'docker login'

cmd_dockerhub_registry_push_latest = \
  'docker push ' \
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  'latest'

cmd_dockerhub_registry_push_version = \
  'docker push ' \
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  "#{@project['version']} "

cmd_dockerhub_registry_tag_latest = \
  'docker tag ' \
  "#{@project['local_user']}/" \
  "#{@project['name']}:" \
  "#{@project['dockerhub_tag']} "\
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  'latest'

cmd_dockerhub_registry_tag_version = \
  'docker tag ' \
  "#{@project['local_user']}/" \
  "#{@project['name']}:" \
  "#{@project['dockerhub_tag']} " \
  "#{@project['dockerhub_user']}/" \
  "#{@project['dockerhub_repo']}:" \
  "#{@project['version']}"

# rubocop:disable Metrics/BlockLength
namespace :dockerhub do |env|
  if task_subtasks env.scope.path
    desc 'Log in to hub.docker.com'
    task :login do
      @commands << cmd_dockerhub_registry_login
    end

    desc 'Push image to hub.docker.com'
    task push: %w[dockerhub:push:version
                  dockerhub:push:latest]
    namespace :push do
      desc 'Push latest image to hub.docker.com'
      task :latest do
        @commands << cmd_dockerhub_registry_push_latest
      end

      desc 'Push version image to hub.docker.com'
      task :version do
        @commands << cmd_dockerhub_registry_push_version
      end
    end

    desc 'Tag image for hub.docker.com'
    task tag: %w[dockerhub:tag:version
                 dockerhub:tag:latest]
    namespace :tag do
      desc 'Tag latest image for hub.docker.com'
      task :latest do
        @commands << cmd_dockerhub_registry_tag_latest
      end
      desc 'Tag version image for hub.docker.com'
      task :version do
        @commands << cmd_dockerhub_registry_tag_version
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength
