# .bashrc

# User specific aliases and functions
alias l='ls -la'

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Add /usr/local/bin to PATH
PATH=$PATH:/usr/local/bin

# Add autocompletion
source <(gopass completion bash)
source <(tau completion bash)
