---
- name: (completion) create completion dir
  ansible.builtin.file:
    path: "{{ takel_takelage_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: (completion) generate tau bash autocompletion
  ansible.builtin.shell: >-
    /usr/local/rvm/wrappers/default/tau completion bash > {{
    takel_takelage_tau_bash_completion }}
  args:
    creates: "{{ takel_takelage_tau_bash_completion }}"

- name: (completion) fix fylla (tau autocompletion library)
  ansible.builtin.copy:
    src: fylla/completion_generator.rb
    # yamllint disable-line rule:line-length
    dest: /usr/local/rvm/gems/ruby-3.0.0/gems/fylla-0.5.1/lib/fylla/completion_generator.rb
    mode: '0644'
    owner: root
    group: rvm
