---
- name: (main) include install
  ansible.builtin.import_tasks: install.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_install

- name: (main) include sudo
  ansible.builtin.import_tasks: sudo.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_sudo

- name: (main) include takelscripts
  ansible.builtin.import_tasks: takelscripts.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_takelscripts

- name: (main) include gnupg
  ansible.builtin.import_tasks: gnupg.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_gnupg

- name: (main) include profile
  ansible.builtin.import_tasks: profile.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_profile

- name: (main) include completion
  ansible.builtin.import_tasks: completion.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_completion

- name: (main) include version
  ansible.builtin.import_tasks: version.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_version
