---
- name: (main) include install
  import_tasks: install.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_install

- name: (main) include sudo
  import_tasks: sudo.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_sudo

- name: (main) include takelscripts
  import_tasks: takelscripts.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_takelscripts

- name: (main) include gnupg
  import_tasks: gnupg.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_gnupg

- name: (main) include profile
  import_tasks: profile.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_profile

- name: (main) include completion
  import_tasks: completion.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_completion

- name: (main) include version
  import_tasks: version.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_version

- name: (main) patch files
  import_tasks: patch.yml
  tags:
    - takel
    - takel_takelage
    - takel_takelage_completion_patch
