# frozen_string_literal: true

require 'rake'

namespace :image do
  namespace :docker do
    namespace :takelbase do
      namespace :base do
        @cmd_image_base.each do |task, command|
          desc 'Build takelbase base image with packer'
          task task do
            @commands << command
          end
        end
      end
    end
  end
end
