---
takel_k3d_deb_install_packages:
  - apt-transport-https
  - ca-certificates
  - kubectl

takel_k3d_google_cloud_repository_key:
  https://packages.cloud.google.com/apt/doc/apt-key.gpg
takel_k3d_google_cloud_repository_keyfile:
  /usr/share/keyrings/kubernetes-archive-keyring.gpg
takel_k3d_google_cloud_repository_filename: kubernetes
takel_k3d_google_cloud_repository_codename: kubernetes-xenial
takel_k3d_google_cloud_repository_url:
  https://apt.kubernetes.io
takel_k3d_google_cloud_repository: >-
  deb [arch=amd64 signed-by={{
  takel_k3d_google_cloud_repository_keyfile }}] {{
  takel_k3d_google_cloud_repository_url }} {{
  takel_k3d_google_cloud_repository_codename }} main

takel_k3d_k3d_version: latest
takel_k3d_k3d_url: >-
  https://github.com/k3d-io/k3d/releases/download/v{{
  takel_k3d_k3d_version }}/k3d-linux-amd64

takel_k3d_bin_path: /usr/local/bin/

takel_k3d_completion_dir: /etc/bash_completion.d
takel_k3d_k3d_bash_completion: >-
  {{ takel_k3d_completion_dir }}/k3d
takel_k3d_kubectl_bash_completion: >-
  {{ takel_k3d_completion_dir }}/kubectl
