---
takel_gcloud_deb_install_packages:
  - bash-completion
  - curl
  - gsutil

takel_gcloud_installation_root: /opt

takel_gcloud_completion_dir: /etc/bash_completion.d
takel_gcloud_bash_completion: "{{ takel_gcloud_completion_dir }}/gcloud"
