---
takel_mutagen_deb_install_packages:
  - bash-completion
  - ca-certificates
  - curl
  - jq

takel_mutagen_mutagen_version: latest

takel_mutagen_curl_download_url:
  /usr/bin/curl -s https://api.github.com/repos/mutagen-io/mutagen/releases | /usr/bin/jq -r '[.[]["assets"][]] | sort_by(.name) | last(.[] | select(.name|test(".*mutagen_linux_.*arm64.*[0-9]+[.][0-9]+.[0-9]+.tar.gz$"))) | .browser_download_url'

takel_mutagen_bin_path: /usr/local/bin/

takel_mutagen_completion_dir: /etc/bash_completion.d
takel_mutagen_bash_completion: >-
  {{ takel_mutagen_completion_dir }}/mutagen

architectures:
  aarch64: arm64
  arm64: arm64
  x86_64: amd64

arch: arm64 # "{{ architectures[ansible_facts['architecture']] | default('noarch') }}"
