---
takel_mutagen_deb_install_packages:
  - bash-completion
  - ca-certificates

takel_mutagen_mutagen_version: latest
takel_mutagen_mutagen_url: >-
  https://github.com/mutagen-io/mutagen/releases/download/v{{
  takel_mutagen_mutagen_version }}/mutagen_linux_{{ arch }}_v{{
  takel_mutagen_mutagen_version }}.tar.gz

takel_mutagen_bin_path: /usr/local/bin/

takel_mutagen_completion_dir: /etc/bash_completion.d
takel_mutagen_bash_completion: >-
  {{ takel_mutagen_completion_dir }}/mutagen
