# frozen_string_literal: true

cmd_img_build_debian_10_systemd = 'docker pull debian:buster-slim ' \
    'mkdir -p packer/images/debian/buster && ' \
    'cd packer && packer build ' \
    "--var 'base_repo=debian' " \
    "--var 'base_tag=buster-slim' " \
    "--var 'target_user=#{@project['local_user']}' " \
    "--var 'target_repo=#{@project['dockerhub_base_tag']}' " \
    "--var 'target_tag=latest' " \
    'templates/base/debian_10_systemd/docker.json'

namespace :image do
  namespace :base do
    desc 'Build Debian buster image with packer'
    task :debian_10_systemd do
      @commands << cmd_img_build_debian_10_systemd
    end
  end
end
