---
- name: (install) install packages
  package:
    name: "{{ takel_pip_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) upgrade pip3
  command: "pip3 install --upgrade pip"
  changed_when: false

- name: (install) install pip packages into venv
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version }}"
    virtualenv: "{{ takel_pip_venv_path }}"
    virtualenv_python: >-
      python{{ takel_pip_venv_python_version | default('3') }}
    virtualenv_site_packages: >-
      {{ takel_pip_venv_global_site_packages | default(false) }}
  when: takel_pip_venv_path is defined
  loop: "{{ takel_pip_packages }}"

- name: (install) install pip packages
  pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version }}"
  when: takel_pip_venv_path is undefined
  loop: "{{ takel_pip_packages }}"

# remove with new version of molecule-docker
# yamllint disable-line rule:line-length
# cf. https://github.services.devops.takamol.support/ansible-community/molecule-docker/commit/009aacd0c3d03b91c4033c5b9c0a57fb8e10c99f#diff-a0d1546c9210b39d0263910adf42b804526d72cfb37e8274f1cdcd9d13151008
- name: (install) workaround until patch is shipped
  lineinfile:
    # yamllint disable-line rule:line-length
    path: /usr/local/lib/python3.9/dist-packages/molecule_docker/playbooks/tasks/delete_network.yml
    regexp: '^    - docker_netname.network.Labels.owner is'
    line: '    - docker_netname.network.Labels.owner is defined'
