---
- name: (install) install packages
  ansible.builtin.apt:
    name: "{{ takel_pip_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) upgrade pip3
  ansible.builtin.command: "pip3 install --upgrade pip"
  changed_when: false

- name: (install) install pip packages into venv
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: forcereinstall
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ takel_pip_venv_path }}"
    virtualenv_python: >-
      python{{ takel_pip_venv_python_version | default('3') }}
    virtualenv_site_packages: >-
      {{ takel_pip_venv_global_site_packages | default(false) }}
  when: takel_pip_venv_path is defined
  loop: "{{ takel_pip_packages }}"

- name: (install) install pip packages
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: present
    version: "{{ item.version | default(omit) }}"
  when: takel_pip_venv_path is undefined
  loop: "{{ takel_pip_packages }}"
