---
- name: (install) install deb packages
  ansible.builtin.apt:
    name: "{{ takel_k3d_deb_install_packages }}"
    state: present
    update_cache: true

- name: (install) download k3d
  ansible.builtin.get_url:
    url: "{{ takel_k3d_k3d_url }}"
    dest: "{{ takel_k3d_bin_path }}/k3d"
    owner: root
    group: root
    mode: 0755
  changed_when: false
