---
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: molecule-takel-rvm-userinstall
    image: takelage/takelslim
    command: /usr/bin/tail -f /dev/null
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_rvm_deb_install_packages:
          - apt-transport-https
          - autoconf
          - automake
          - bison
          - bzip2
          - ca-certificates
          - curl
          - g++
          - gawk
          - gcc
          - git
          - gnupg
          - libc6-dev
          - libffi-dev
          - libgdbm-dev
          - libgmp-dev
          - libncurses5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libssl-dev
          - libtool
          - libyaml-dev
          - make
          - patch
          - pkg-config
          - procps
          - sqlite3
          - sudo
          - zlib1g-dev
        takel_rvm_user: ruby
        takel_rvm_install_path: ~/.rvm
        takel_rvm_rvm_install_flags: --ignore-dotfiles --user-install
        takel_rvm_rubies:
          - ruby-2.7
          - ruby-3
        takel_rvm_autolib_mode: 2
verifier:
  name: testinfra
  options:
    # p: cacheprovider  # enable cache
    s: true  # capture output
  additional_files_or_dirs:
    - ../../default/*/test_*.py
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
