require 'rake'

cmd_takelscripts_unit = 'cd ansible/roles/takel-takelage/files/takelscripts/test && ' +
        'pytest -v'

namespace :takelscripts do

  desc 'Run unit tests'
  task :unit do
    $commands << cmd_takelscripts_unit
  end

end
