require 'rake'

cmd_scripts_unit = 'cd ansible/roles/takel-takelage/files/takelscripts/test && ' +
        'pytest -v'

namespace :scripts do

  desc 'Run unit tests'
  task :unit do
    $commands << cmd_scripts_unit
  end

end
