---
- name: (completion) create completion dir
  file:
    path: "{{ takel_molecule_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: (completion) copy completion file
  copy:
    src: molecule
    dest: "{{ takel_molecule_bash_completion }}"
    owner: root
    group: root
    mode: 0644
