---
- name: (completion) create completion dir
  ansible.builtin.file:
    path: "{{ takel_molecule_completion_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: (completion) copy completion file
  ansible.builtin.copy:
    src: molecule
    dest: "{{ takel_molecule_bash_completion }}"
    owner: root
    group: root
    mode: '0644'
