---
- name: (playbook-site) create project
  hosts: all
  roles:
    # system
    - takel-base
    - takel-root
    - takel_anarchism
    - takel-mutagen
    # mercurial
    - takel_hg
    # python
    - takel-pip
    - takel-molecule
    # docker
    - takel-docker
    # packer
    - takel-packer
    # gopass
    - takel-gopass
    # hugo
    - takel-hugo
    # ruby
    - takel-gem
    # takelage
    - takel-takelage
    - takel_cleanup
