---
- name: (playbook-site) create project
  hosts: all
  roles:
    # system
    - takel_base
    - takel_root
    - takel_anarchism
    - takel_mutagen
    # mercurial
    - takel_hg
    # python
    - takel_pip
    - takel_molecule
    # docker
    - takel_docker
    # packer
    - takel_packer
    # gopass
    - takel_gopass
    # hugo
    - takel_hugo
    # ruby
    - takel_gem
    # takelage
    - takel_takelage
    - takel_cleanup
