---
- name: (playbook-site) create project
  hosts: all
  roles:
    # system
    - takel-base
    - takel-root
    - takel-anarchism
    - takel-mutagen
    # python
    - takel-pip
    - takel-molecule
    # docker
    - takel-docker
    # packer
    - takel-packer
    # gopass
    - takel-gopass
    # bit
    - takel-bit-client
    # gcloud
    - takel-gcloud
    # hugo
    - takel-hugo
    # terra
    - takel-terra
    # ruby
    - takel-rvm
    - takel-gem
    # takelage
    - takel-takelage
    - takel-cleanup
