# frozen_string_literal: true

require 'rake'

cmd_takelbase_docker_pull = 'docker pull ' \
    "#{@project['dockerhub_base_user']}/" \
    "#{@project['dockerhub_base_repo']}:" \
    'latest'

namespace :image do
  namespace :docker do
    namespace :takelbase do
      desc 'Update takelbase docker image'
      task :update do
        @commands << cmd_takelbase_docker_pull
      end
    end
  end
end
