---
- name: default
  hosts: all
  pre_tasks:
    - name: (converge) install prerequisites
      ansible.builtin.apt:
        name: "{{ item }}"
      loop:
        - python3-yaml
  roles:
    - takel_gem
    - takel_docker
    - takel_takelage
