---
driver:
  name: docker
platforms:
  - name: molecule-takel-takelage
    image: takelwerk/takelslim
    command: /usr/bin/tail -f /dev/null
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    group_vars:
      all:
        takel_takelage_version: 0.0.1
        takel_gem_gems:
          - name: takeltau
            version: 0.40.0
            description: takelage cli
verifier:
  name: testinfra
  options:
    s: true
  additional_files_or_dirs:
    - ../system/test_*.py
scenario:
  create_sequence:
    - create
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
