---
# installed via github
takel_kubernetes_k3d_install: true
# installed via github
takel_kubernetes_helm_install: true
# installed via apt repo
takel_kubernetes_kubectl_install: true
# needed for kubectl
takel_kubernetes_google_cloud_repository_install: true

# general
takel_kubernetes_deb_install_packages:
  - apt-transport-https
  - ca-certificates
  - curl
takel_kubernetes_bin_path: /usr/local/bin
takel_kubernetes_completion_dir: /etc/bash_completion.d

# k3d
takel_kubernetes_k3d_version: latest
takel_kubernetes_k3d_url: >-
  https://github.com/k3d-io/k3d/releases/download/v{{
  takel_kubernetes_k3d_version }}/k3d-linux-{{ arch }}
takel_kubernetes_k3d_bin: "{{ takel_kubernetes_bin_path }}/k3d"
takel_kubernetes_k3d_completion: >-
  {{ takel_kubernetes_completion_dir }}/k3d

# helm
takel_kubernetes_helm_version: latest
takel_kubernetes_helm_download_file: >-
  helm-{{ takel_kubernetes_helm_version }}-linux-{{ arch }}.tar.gz
takel_kubernetes_helm_url: >-
  https://get.helm.sh/{{ takel_kubernetes_helm_download_file }}
takel_kubernetes_helm_tmp_dir: /tmp
takel_kubernetes_helm_tmp_targz: >-
  {{ takel_kubernetes_helm_tmp_dir }}/{{
  takel_kubernetes_helm_download_file }}
takel_kubernetes_helm_tmp_targz_dir: >-
  {{ takel_kubernetes_helm_tmp_dir }}/linux-{{ arch }}
takel_kubernetes_helm_tmp_bin: >-
  {{ takel_kubernetes_helm_tmp_targz_dir }}/helm
takel_kubernetes_helm_bin: "{{ takel_kubernetes_bin_path }}/helm"
takel_kubernetes_helm_completion: >-
  {{ takel_kubernetes_completion_dir }}/helm

# kubectl
takel_kubernetes_kubectl_deb_install_package:
  - kubectl
takel_kubernetes_kubectl_completion: >-
  {{ takel_kubernetes_completion_dir }}/kubectl
takel_kubernetes_kubectl_version: 1.29

takel_kubernetes_k3d_version_cmd: curl -s https://github.com/k3d-io/k3d/releases | grep '/k3d-io/k3d/releases/tag/' | head -1 | sed -E 's#.*">v(.*)</a>.*#\1#'  # yamllint disable-line rule:line-length
takel_kubernetes_helm_version_cmd: curl -s https://github.com/helm/helm/releases | grep '/helm/helm/releases/tag/' | grep -v "\-rc" | head -1 | sed -E 's#.*">Helm (.*)</a>.*#\1#'  # yamllint disable-line rule:line-length

# google kubernetes repo
takel_kubernetes_google_cloud_repository_key: >-
  https://pkgs.k8s.io/core:/stable:/v{{
  takel_kubernetes_kubectl_version }}/deb/Release.key
takel_kubernetes_google_cloud_repository_keyfile_tmp:
  /tmp/kubernetes-archive-keyring.gpg.asc
takel_kubernetes_google_cloud_repository_keyfile:
  /usr/share/keyrings/kubernetes-archive-keyring.gpg
takel_kubernetes_google_cloud_repository_filename: kubernetes
takel_kubernetes_google_cloud_repository_url: >-
  https://pkgs.k8s.io/core:/stable:/v{{
  takel_kubernetes_kubectl_version }}/deb/
takel_kubernetes_google_cloud_repository: >-
  deb [arch={{ arch }} signed-by={{
  takel_kubernetes_google_cloud_repository_keyfile }}] {{
  takel_kubernetes_google_cloud_repository_url }} /

architectures:
  aarch64: arm64
  arm64: arm64
  x86_64: amd64

arch: "{{ architectures[ansible_facts['architecture']] | default('noarch') }}"
