require 'rake'

cmd_image_prod_build = "cd packer && packer build " +
    "--var 'ansible_environment=prod' " +
    "--var 'ansible_playbook=playbook-project-prod.yml' " +
    "--var 'base_image=#{$project['base_image']}' " +
    "--var 'base_tag=latest' " +
    "--var 'repo_local=#{$project['repo_local']}' " +
    "--var 'image_name=#{$project['project']}' " +
    "--var 'image_tag=prod' " +
    "templates/project/docker.json"

cmd_image_prod_test = 'cd ansible && molecule test --scenario-name img_prod'

namespace :image do
  namespace :prod do

    desc 'Build production image'
    task :build do
      $commands << cmd_image_prod_build
    end

    desc 'Test production image'
    task :test do
      $commands << cmd_image_prod_test
    end

  end
end