---
- name: (configure) create completion dir
  file:
    path: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: 0755

# https://gohugo.io/commands/hugo_gen_autocomplete/
- name: (configure) add hugo autocompletion
  shell: >-
    hugo gen autocomplete > /etc/profile.d/{{
    takel_hugo_profile_order }}hugo
  args:
    creates: "/etc/profile.d/{{ takel_hugo_profile_order }}hugo"
