require 'rake'

namespace :dockerhub do
  desc 'Create and deploy prod image to dockerhub'
  task :prod => %w(git:warn
                   test:project
                   image:prod:build
                   image:prod:test
                   git:tag
                   dockerhub:prod:registry:tag
                   dockerhub:prod:registry:login
                   dockerhub:prod:registry:push)
end
