---
name: Test arm64

on:
  workflow_dispatch:  # allow manual trigger

jobs:
  test-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
