---
name: Test arm64

on:
  workflow_dispatch:  # allow manual trigger

jobs:
  test-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create randmac.py
        run: |
          cat << EOF > $HOME/randmac.py
          #!/usr/bin/env python3
          import random
          def randomMAC():
            return [ 0x00, 0x16, 0x3e,
            random.randint(0x00, 0x7f),
            random.randint(0x00, 0xff),
            random.randint(0x00, 0xff) ]
          def MACprettyprint(mac):
            return ':'.join(map(lambda x: "%02x" % x, mac))
          if __name__ == '__main__':
            print(MACprettyprint(randomMAC()))
          EOF

      - name: Create cloud init config
        run: |
          cat << EOF > user-data
          #cloud-config
          password: ubuntu
          chpasswd: { expire: False }
          ssh_pwauth: True
          EOF

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
