---
name: test roles

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  test-roles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install mutagen
        run: |
          wget --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -O /tmp/mutagen.tar.gz https://github.com/mutagen-io/mutagen/releases/download/v0.17.0/mutagen_linux_amd64_v0.17.0.tar.gz
          sudo tar xvfz /tmp/mutagen.tar.gz -C /usr/local/bin
          mutagen daemon start

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Install tau
        run: gem install takeltau

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass --no-gpg --no-ssh" >> $HOME/.takelage.yml
          echo "docker_repo: takelbuild" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Test roles
        run: tau docker container command "ANSIBLE_ROLES_PATH=/project/ansible/roles rake ansible:roles:each"
